import { useState, useRef, useEffect } from 'react'
import {
  RadarChart, Radar, PolarGrid, PolarAngleAxis, ResponsiveContainer,
} from 'recharts'
import { Download } from 'lucide-react'
import InfoTip from './InfoTip'

const IC_LEVEL_LABELS = { 1: 'Invest', 2: 'Need More Diligence', 3: 'Watchlist', 4: 'Pass' }

// ── Memo generator ────────────────────────────────────────────────────────────
function generateMemo(profile, synthesis, agentScores, icSuggestion, icVerdict) {
  if (!synthesis) return null
  const name = profile?.company_name ?? 'Company'
  const scored = agentScores.filter(a => a.score != null)

  let icSection = ''
  if (icSuggestion) {
    const aiLabel = IC_LEVEL_LABELS[icSuggestion.level] ?? 'Unknown'
    const userLabel = icVerdict ? IC_LEVEL_LABELS[icVerdict] : null
    icSection = `
## IC Committee Decision

**AI Recommendation:** ${aiLabel}
${userLabel ? `**Your Verdict:** ${userLabel}` : ''}

${icSuggestion.reasoning ?? ''}
${Array.isArray(icSuggestion.rationale_points) && icSuggestion.rationale_points.length > 0
    ? '\n### Key Rationale\n\n' + icSuggestion.rationale_points.map(p => `- ${p}`).join('\n')
    : ''}
${Array.isArray(icSuggestion.red_flags) && icSuggestion.red_flags.length > 0
    ? '\n### Red Flags\n\n' + icSuggestion.red_flags.map(f => `- ${f}`).join('\n')
    : ''}
${Array.isArray(icSuggestion.questions_for_founders) && icSuggestion.questions_for_founders.length > 0
    ? '\n### Questions for Founders\n\n' + icSuggestion.questions_for_founders.map((q, i) => `${i + 1}. ${q}`).join('\n')
    : ''}`
  }

  return `# ${name} — Due Diligence Memo

## Executive Summary

${name} ${profile?.description ?? ''}

**Stage:** ${profile?.stage ?? 'N/A'} | **Funding Ask:** ${profile?.funding_ask ?? 'N/A'} | **Location:** ${profile?.location ?? 'N/A'}

## Key Strengths

${synthesis.key_strengths?.map(s => `- ${s}`).join('\n') ?? ''}

## Key Risks

${synthesis.key_concerns?.map(c => `- ${c}`).join('\n') ?? ''}

## Agent Evaluation Summary

${scored.map(a => `- **${a.label}**: ${a.score}/100 — ${a.analysis ?? ''}`).join('\n')}

## Investment Recommendation

**${synthesis.recommendation}**

${synthesis.recommendation_detail ?? ''}

Overall Diligence Score: **${synthesis.overall_score}/100**
${icSection}

## Suggested Questions for Next Meeting

${synthesis.suggested_questions?.map((q, i) => `${i + 1}. ${q}`).join('\n') ?? ''}

---
*Generated by DueDeck — AI-powered venture due diligence*
`
}

// ── Simple markdown renderer ──────────────────────────────────────────────────
function Inline({ text }) {
  const parts = String(text).split(/(\*\*[^*]+\*\*)/)
  return (
    <>
      {parts.map((p, i) =>
        p.startsWith('**') ? <strong key={i} className="font-semibold text-gray-800">{p.slice(2, -2)}</strong> : p
      )}
    </>
  )
}

function MarkdownView({ content }) {
  const blocks = content.split('\n')
  const els = []
  let i = 0
  while (i < blocks.length) {
    const line = blocks[i]
    if (line.startsWith('# '))       { els.push(<h1 key={i} className="text-sm font-bold text-gray-900 mt-3 mb-1">{line.slice(2)}</h1>) }
    else if (line.startsWith('## ')) { els.push(<h2 key={i} className="text-xs font-semibold text-gray-700 mt-2.5 mb-1 border-b border-gray-100 pb-0.5">{line.slice(3)}</h2>) }
    else if (line.startsWith('- '))  {
      const items = []
      while (i < blocks.length && blocks[i].startsWith('- ')) { items.push(blocks[i].slice(2)); i++ }
      els.push(<ul key={`ul${i}`} className="list-disc list-inside space-y-0.5 mb-1">{items.map((t, j) => <li key={j} className="text-xs text-gray-600"><Inline text={t} /></li>)}</ul>)
      continue
    } else if (/^\d+\. /.test(line)) {
      const items = []
      while (i < blocks.length && /^\d+\. /.test(blocks[i])) { items.push(blocks[i].replace(/^\d+\. /, '')); i++ }
      els.push(<ol key={`ol${i}`} className="list-decimal list-inside space-y-0.5 mb-1">{items.map((t, j) => <li key={j} className="text-xs text-gray-600"><Inline text={t} /></li>)}</ol>)
      continue
    } else if (line.trim() === '')   { els.push(<div key={i} className="h-1" />) }
    else                              { els.push(<p key={i} className="text-xs text-gray-600 leading-relaxed"><Inline text={line} /></p>) }
    i++
  }
  return <div>{els}</div>
}

// ── Download helpers ──────────────────────────────────────────────────────────
function downloadMd(content, name) {
  const a = document.createElement('a')
  a.href = URL.createObjectURL(new Blob([content], { type: 'text/markdown' }))
  a.download = `${name ?? 'memo'}_diligence_memo.md`
  a.click()
}

function downloadPdf(content, name) {
  const w = window.open('', '_blank')
  const html = content
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n/g, '<br>')
  w.document.write(`<html><head><title>${name} Diligence Memo</title>
<style>body{font-family:Georgia,serif;max-width:800px;margin:40px auto;line-height:1.7;font-size:14px}
h1{font-size:20px;font-weight:700;margin:24px 0 8px}h2{font-size:15px;color:#374151;border-bottom:1px solid #e5e7eb;padding-bottom:4px;margin:20px 0 6px}
li{margin-bottom:4px}strong{color:#111}</style></head><body>${html}</body></html>`)
  w.document.close(); w.print()
}

const AGENT_SUBJECTS = ['Team','Market','Product','Traction','Business Model','Competition','Financials','Risk']

// ── Main export ───────────────────────────────────────────────────────────────
export default function Row3Panels({ agentScores, synthesis, profile, icSuggestion, icVerdict }) {
  const memo = generateMemo(profile, synthesis, agentScores, icSuggestion, icVerdict)
  const companyName = profile?.company_name ?? 'Company'
  const [showDl, setShowDl] = useState(false)
  const dlRef = useRef(null)
  useEffect(() => {
    function onClickOutside(e) { if (dlRef.current && !dlRef.current.contains(e.target)) setShowDl(false) }
    document.addEventListener('mousedown', onClickOutside)
    return () => document.removeEventListener('mousedown', onClickOutside)
  }, [])

  const radarData = AGENT_SUBJECTS.map((subject, i) => ({
    subject,
    You: agentScores[i]?.score ?? 0,
  }))

  return (
    <div className="grid grid-cols-2 gap-3">

      {/* Panel 1 — Radar */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-4 flex flex-col" style={{ height: 380 }}>
        <div className="flex items-center gap-1.5 mb-2">
          <span className="text-sm font-semibold text-gray-800">Investment Dimension Radar</span>
          <InfoTip text="Radar chart visualising this company's scores across 8 investment dimensions." />
        </div>
        <ResponsiveContainer width="100%" height="100%">
          <RadarChart data={radarData} margin={{ top: 10, right: 28, bottom: 10, left: 28 }}>
            <PolarGrid stroke="#e5e7eb" />
            <PolarAngleAxis dataKey="subject" tick={{ fontSize: 9, fill: '#6b7280' }} />
            <Radar name="You" dataKey="You" stroke="#8b5cf6" fill="#8b5cf6" fillOpacity={0.18} strokeWidth={2} dot={{ r: 3 }} />
          </RadarChart>
        </ResponsiveContainer>
      </div>

      {/* Panel 2 — Diligence Memo */}
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 flex flex-col overflow-hidden" style={{ height: 380 }}>
        <div className="flex items-center justify-between px-4 pt-4 pb-2 flex-shrink-0">
          <div className="flex items-center gap-1.5">
            <span className="text-sm font-semibold text-gray-800">Diligence Memo</span>
            <InfoTip text="Auto-generated executive memo summarising key strengths, risks, agent scores, investment recommendation, and suggested questions for your next meeting." />
          </div>
          {memo && (
            <div className="relative" ref={dlRef}>
              <button
                onClick={() => setShowDl(v => !v)}
                className="flex items-center gap-1 text-xs text-gray-500 border border-gray-200 rounded-lg px-2.5 py-1 hover:bg-gray-50"
              >
                <Download size={11} /> Download
                <svg width="8" height="8" viewBox="0 0 24 24" fill="none"><path d="M6 9l6 6 6-6" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>
              </button>
              {showDl && (
                <div className="absolute right-0 top-full mt-1 bg-white border border-gray-100 rounded-xl shadow-lg overflow-hidden z-20">
                  <button onClick={() => { downloadMd(memo, companyName); setShowDl(false) }}
                    className="block w-full text-left px-3 py-2 text-xs text-gray-700 hover:bg-gray-50 whitespace-nowrap">
                    Download as Markdown (.md)
                  </button>
                  <button onClick={() => { downloadPdf(memo, companyName); setShowDl(false) }}
                    className="block w-full text-left px-3 py-2 text-xs text-gray-700 hover:bg-gray-50 whitespace-nowrap">
                    Download as PDF (print)
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
        <div className="flex-1 min-h-0 overflow-y-auto px-4 pb-4 font-mono text-xs">
          {memo ? (
            <MarkdownView content={memo} />
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-gray-300 gap-2">
              <svg width="28" height="28" fill="none" viewBox="0 0 24 24"><path d="M9 12h6M9 16h6M6 4h9l4 4v14H6V4z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></svg>
              <p className="text-xs text-center">Memo will appear here<br/>after analysis completes</p>
            </div>
          )}
        </div>
      </div>

    </div>
  )
}
